enum authEnum {
    LOGIN_FAIL = "LOGIN_FAIL",
    LOGIN_SUCCESS= "LOGIN_SUCCESS",

    REGISTER_FAIL= "REGISTER_FAIL",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",

    REQUESTING_USER = "REQUESTING_USER",
    REQUESTING_USER_FAIL = "REQUESTING_USER_FAIL",

    UPDATE_USER = "UPDATE_USER",
    UPDATE_USER_FAIL = "UPDATE_USER_FAIL",

    DELETE_USER = "DELETE_USER",
    DELETE_USER_FAIL = "DELETE_USER_FAIL",

    SET_MESSAGE = "SET_MESSAGE",
    CLEAR_MESSAGE = "CLEAR_MESSAGE",

    LOGOUT = "LOGOUT"
}

export {
    authEnum
}